main = "src/index.ts"

compatibility_date = "2024-09-02"

compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "KV"
id = "824d7f1ff2ce43b1a00333897e46bf55"

[[r2_buckets]]
binding = "R2"
bucket_name = "test-otel-bucket"

[[d1_databases]]
binding = "DB"
database_name = "test-otel-d1"
database_id = "69dc4b67-52ce-48d2-8f4d-05328bd901f4"
